PX-1350 Add logic to skip integration/unit tests
ebot7/eb7-sls-helper pull request #30
Opened 2021-03-22 13:43 UTC by maxim-ebot7

2021-03-22 18:03 UTC, hasan-dot requested changes

2021-03-22 18:03 UTC, hasan-dot commented on eb7_sls_helper/src/gh_action_interface.py
> +    serverless_config = read_serverless_config(' '.join(sls))
you can remove the join as it is not needed 
```suggestion
    serverless_config = read_serverless_config(sls)
```

2021-03-23 09:21 UTC, hasan-dot commented on eb7_sls_helper/src/gh_action_interface.py
> +    serverless_config = read_serverless_config(' '.join(sls))
we return list, not string

2021-03-23 09:22 UTC, hasan-dot approved these changes

2021-03-23 13:04 UTC, paolo-rechia approved these changes
LGTM

2021-03-23 16:11 UTC, merged