PX-1429: adding an extra check in the case of not having tests
ebot7/eb7-sls-helper pull request #36
Opened 2021-03-24 12:00 UTC by GeylaniBerk

2021-03-24 17:11 UTC, paolo-rechia requested changes
I'd change this to give us a more meaningful messages:

1.`Unit tests skipped because serverless file was not found.`
2.`Unit tests skipped because "skipUnitTests" flag was turned on.`

2021-03-25 08:39 UTC, maxim-ebot7 commented on eb7_sls_helper/src/gh_action_interface.py
> +        if not skip_unit_tests and sls:
Why do we check the sls file?(serverless.yml)

Should we check tox.ini is missing instead? Or what's the flow here?

2021-03-25 08:42 UTC, paolo-rechia commented on eb7_sls_helper/src/gh_action_interface.py
> +        if not skip_unit_tests and sls:
That could also work. Missing serverless file could skip everything, right?

2021-03-25 08:43 UTC, paolo-rechia commented on eb7_sls_helper/src/gh_action_interface.py
> +        if not skip_unit_tests and sls:
Now that you mention, we should also fix this for integration tests. We can move the check a few lines above, before trying to run any of these blocks, I think. Except maybe for linter?

2021-03-25 10:11 UTC, GeylaniBerk commented on eb7_sls_helper/src/gh_action_interface.py
> +        if not skip_unit_tests and sls:
I added check before deploy, integration test and unit test

2021-03-25 10:31 UTC, paolo-rechia approved these changes
LGTM

2021-03-25 10:56 UTC, merged

2021-03-25 10:59 UTC, zvonimir-ebot7 commented on eb7_sls_helper/src/gh_action_interface.py
> +            set_output(f"formatted", "Integration tests skipped because 'skipIntegrationTests'' flag was turned on.")
I would move these checks out of the `__name__ == "__main__"` block, which is already too complex.