Local sls runs and other enhancements
ebot7/eb7-sls-helper pull request #46
Opened 2021-03-26 18:07 UTC by zvonimir-ebot7

2021-04-07 11:24 UTC, paolo-rechia approved these changes
LGTM.

Thanks for this, seems like we got some good improvements out of this PR. I'd still like to test this before we merge though (on QA) phase.

2021-04-07 13:35 UTC, hasan-dot requested changes

2021-04-07 13:35 UTC, hasan-dot commented on eb7_sls_helper/src/newman.py
> +def verify_postman_collection(postman_key: str, collection: str) -> bool:
the 3 verify methods are only being used here so we can append an underscore "`_`" to the name to be like
```suggestion
        if not _verify_postman_key(postman_api_key):
            output += b"\nPostman API key verification failed!"
        elif not _verify_postman_collection(postman_api_key, collection):
            output += b"\nPostman Collection UID verification failed!"
        elif not _verify_postman_environment(postman_api_key, environment):
            output += b"\nPostman Environment UID verification failed!"

    filtered_cmd = [s.replace(postman_api_key, "****") for s in cmd]
    return filtered_cmd, output.decode("utf-8"), error, return_code


def _verify_postman_key(postman_key: str) -> bool:
    """Verify the postman key by sending an HTTP request to Postman."""
    return _verify_url(
        f"https://api.getpostman.com/collections?apikey={postman_key}"
    )


def _verify_postman_environment(postman_key: str, environment: str) -> bool:
    """Verify the environment UID by sending an HTTP request to Postman."""
    return _verify_url(
        f"https://api.getpostman.com/environments/{environment}?apikey={postman_key}",
    )


def _verify_postman_collection(postman_key: str, collection: str) -> bool:
```

2021-04-07 13:37 UTC, hasan-dot approved these changes
Looks good to me but added some suggestions
Great Work @zvonimir-ebot7

2021-04-12 07:28 UTC, zvonimir-ebot7 commented on eb7_sls_helper/src/gh_action_interface.py
> +        base_loglevel (int): values between 0 and 50 are expected.
Fixed.

2021-04-12 07:29 UTC, zvonimir-ebot7 commented on eb7_sls_helper/src/gh_action_interface.py
> +        # required=not os.environ.get("INPUT_STAGE"),
Fixed.

2021-04-12 07:29 UTC, zvonimir-ebot7 commented on eb7_sls_helper/src/gh_action_interface.py
> +        # required=not os.environ.get("INPUT_PROFILE"),
Fixed.

2021-04-12 07:29 UTC, zvonimir-ebot7 commented on eb7_sls_helper/src/gh_action_interface.py
> +        # required=not os.environ.get("INPUT_AWS_ACCESS_KEY_ID"),
Fixed.

2021-04-12 07:29 UTC, zvonimir-ebot7 commented on eb7_sls_helper/src/gh_action_interface.py
> +        # required=not os.environ.get("INPUT_AWS_SECRET_ACCESS_KEY"),
Fixed.

2021-04-12 07:30 UTC, zvonimir-ebot7 commented on eb7_sls_helper/src/gh_action_interface.py
> +        ],
Fixed.

2021-04-12 07:35 UTC, zvonimir-ebot7 commented on eb7_sls_helper/src/newman.py
> +def verify_postman_collection(postman_key: str, collection: str) -> bool:
I was thinking the same way. They were actually named that way initially. But then I thought we might want to use these functions from the outside. E.g. it would make sense to verify these things when calling `sls_helper --validate`. I'll leave the _public_ names for now, although I did not change the behaviour of `--validate` yet.

2021-04-12 07:40 UTC, merged